from typing import Optional
from pydantic import BaseModel
from pydantic_sqlalchemy import sqlalchemy_to_pydantic
from models.UserPermissionGroup import UserPermissionGroup

UserPermissionGroupBase = sqlalchemy_to_pydantic(UserPermissionGroup)
